In [19]:
import pandas as pd
import numpy as np
import re

In [20]:
books_original = pd.read_csv('data/Books.csv')
books_original.head()

/var/folders/zc/51jtshy91712t6pn90n8n0mr0000gn/T/ipykernel_68268/2291626495.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books_original = pd.read_csv('data/Books.csv')

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [21]:
# Make a new column in books with all characters in lowercase and without special characters
books = books_original.copy()
books['Book-Title-Modified'] = books['Book-Title'].str.lower()
books['Book-Title-Modified'] = books['Book-Title'].str.replace(r'\W', '', regex=True)
books['Book-Title-Modified'] = books['Book-Title-Modified'].str.replace(r'\s+', ' ', regex=True)

print("Number of unique titles in the original dataset:", books['Book-Title'].nunique())
print("Number of unique modified titles in the dataset:", books['Book-Title-Modified'].nunique())


# books.to_csv('data/cleaned_books_modified.csv', index=False)

Number of unique titles in the original dataset: 242135
Number of unique modified titles in the dataset: 239878

In [22]:
print("Number of records in the original dataset:", books_original.shape[0])

Number of records in the original dataset: 271360

In [23]:
# Sort the dataset by author name
books = books.sort_values(by='Book-Author')
books.head(10)

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L,Book-Title-Modified
18118,0312956762,Die Hard: With a Vengeance - A Novel,D. Chiel,1995,St Martins Pr,http://images.amazon.com/images/P/0312956762.0...,http://images.amazon.com/images/P/0312956762.0...,http://images.amazon.com/images/P/0312956762.0...,DieHardWithaVengeanceANovel
232912,034545006X,The Taking,J. D. Landis,2003,Ballantine Books,http://images.amazon.com/images/P/034545006X.0...,http://images.amazon.com/images/P/034545006X.0...,http://images.amazon.com/images/P/034545006X.0...,TheTaking
107022,1579651372,Ruskin's Rose: A Venetian Love Story,Mimma Balia,2000,Artisan Publishers,http://images.amazon.com/images/P/1579651372.0...,http://images.amazon.com/images/P/1579651372.0...,http://images.amazon.com/images/P/1579651372.0...,RuskinsRoseAVenetianLoveStory
99357,0440416361,Nsync : The Official Book,'N Sync,1998,Delacorte Press,http://images.amazon.com/images/P/0440416361.0...,http://images.amazon.com/images/P/0440416361.0...,http://images.amazon.com/images/P/0440416361.0...,NsyncTheOfficialBook
224536,0972066713,The Mom-to-Mom Guide to the Baby Years: Review...,142 moms from all over the world,2002,"Sound Bite Press, Inc.",http://images.amazon.com/images/P/0972066713.0...,http://images.amazon.com/images/P/0972066713.0...,http://images.amazon.com/images/P/0972066713.0...,TheMomtoMomGuidetotheBabyYearsReviewsRatingsan...
87995,055301000X,"\A new spirit, a new commitment, a new America...",1977 Inaugural Committee (U.S.),1977,Bantam Books,http://images.amazon.com/images/P/055301000X.0...,http://images.amazon.com/images/P/055301000X.0...,http://images.amazon.com/images/P/055301000X.0...,AnewspiritanewcommitmentanewAmericaTheinaugura...
135777,0874063582,Friendship for Three,1st Graders of Samuel s Nixon School Carnegie ...,1988,Pages Publishing Group,http://images.amazon.com/images/P/0874063582.0...,http://images.amazon.com/images/P/0874063582.0...,http://images.amazon.com/images/P/0874063582.0...,FriendshipforThree
209538,078946697X,"DK Readers: Creating the X-Men, How It All Beg...",2000,DK Publishing Inc,http://images.amazon.com/images/P/078946697X.0...,http://images.amazon.com/images/P/078946697X.0...,http://images.amazon.com/images/P/078946697X.0...,NaN,DKReadersCreatingtheXMenHowItAllBeganLevel4Pro...
221678,0789466953,"DK Readers: Creating the X-Men, How Comic Book...",2000,DK Publishing Inc,http://images.amazon.com/images/P/0789466953.0...,http://images.amazon.com/images/P/0789466953.0...,http://images.amazon.com/images/P/0789466953.0...,NaN,DKReadersCreatingtheXMenHowComicBooksCometoLif...
220731,2070426769,"Peuple du ciel, suivi de 'Les Bergers\"";Jean-M...",2003,Gallimard,http://images.amazon.com/images/P/2070426769.0...,http://images.amazon.com/images/P/2070426769.0...,http://images.amazon.com/images/P/2070426769.0...,NaN,PeupleducielsuivideLesBergersJeanMarieGustaveL...

In [24]:
# Give common ISBN to books with the same title and author
books['ISBN_new'] = books.groupby(['Book-Title-Modified']).ngroup()
books.head(10)

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L,Book-Title-Modified,ISBN_new
18118,0312956762,Die Hard: With a Vengeance - A Novel,D. Chiel,1995,St Martins Pr,http://images.amazon.com/images/P/0312956762.0...,http://images.amazon.com/images/P/0312956762.0...,http://images.amazon.com/images/P/0312956762.0...,DieHardWithaVengeanceANovel,50519
232912,034545006X,The Taking,J. D. Landis,2003,Ballantine Books,http://images.amazon.com/images/P/034545006X.0...,http://images.amazon.com/images/P/034545006X.0...,http://images.amazon.com/images/P/034545006X.0...,TheTaking,208690
107022,1579651372,Ruskin's Rose: A Venetian Love Story,Mimma Balia,2000,Artisan Publishers,http://images.amazon.com/images/P/1579651372.0...,http://images.amazon.com/images/P/1579651372.0...,http://images.amazon.com/images/P/1579651372.0...,RuskinsRoseAVenetianLoveStory,151838
99357,0440416361,Nsync : The Official Book,'N Sync,1998,Delacorte Press,http://images.amazon.com/images/P/0440416361.0...,http://images.amazon.com/images/P/0440416361.0...,http://images.amazon.com/images/P/0440416361.0...,NsyncTheOfficialBook,131167
224536,0972066713,The Mom-to-Mom Guide to the Baby Years: Review...,142 moms from all over the world,2002,"Sound Bite Press, Inc.",http://images.amazon.com/images/P/0972066713.0...,http://images.amazon.com/images/P/0972066713.0...,http://images.amazon.com/images/P/0972066713.0...,TheMomtoMomGuidetotheBabyYearsReviewsRatingsan...,197450
87995,055301000X,"\A new spirit, a new commitment, a new America...",1977 Inaugural Committee (U.S.),1977,Bantam Books,http://images.amazon.com/images/P/055301000X.0...,http://images.amazon.com/images/P/055301000X.0...,http://images.amazon.com/images/P/055301000X.0...,AnewspiritanewcommitmentanewAmericaTheinaugura...,13875
135777,0874063582,Friendship for Three,1st Graders of Samuel s Nixon School Carnegie ...,1988,Pages Publishing Group,http://images.amazon.com/images/P/0874063582.0...,http://images.amazon.com/images/P/0874063582.0...,http://images.amazon.com/images/P/0874063582.0...,FriendshipforThree,70585
209538,078946697X,"DK Readers: Creating the X-Men, How It All Beg...",2000,DK Publishing Inc,http://images.amazon.com/images/P/078946697X.0...,http://images.amazon.com/images/P/078946697X.0...,http://images.amazon.com/images/P/078946697X.0...,NaN,DKReadersCreatingtheXMenHowItAllBeganLevel4Pro...,42578
221678,0789466953,"DK Readers: Creating the X-Men, How Comic Book...",2000,DK Publishing Inc,http://images.amazon.com/images/P/0789466953.0...,http://images.amazon.com/images/P/0789466953.0...,http://images.amazon.com/images/P/0789466953.0...,NaN,DKReadersCreatingtheXMenHowComicBooksCometoLif...,42577
220731,2070426769,"Peuple du ciel, suivi de 'Les Bergers\"";Jean-M...",2003,Gallimard,http://images.amazon.com/images/P/2070426769.0...,http://images.amazon.com/images/P/2070426769.0...,http://images.amazon.com/images/P/2070426769.0...,NaN,PeupleducielsuivideLesBergersJeanMarieGustaveL...,139173

In [25]:
books.ISBN_new.nunique()

239878

In [26]:
books["Book-Title"].nunique()

242135

In [27]:
# Modify the ISBNs in the ratings dataset
ratings = pd.read_csv('data/Ratings.csv')

# ratings = ratings.merge(books[['ISBN', 'ISBN_new']], on='ISBN', how='left')
# ratings = ratings.drop(columns=['ISBN'])
# ratings = ratings.rename(columns={'ISBN_new': 'ISBN'})
ratings.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [28]:
# Create a mapping from ISBN to ISBN_new
isbn_mapping = books[['ISBN', 'ISBN_new']].drop_duplicates()
isbn_mapping.head()

              ISBN  ISBN_new
18118   0312956762     50519
232912  034545006X    208690
107022  1579651372    151838
99357   0440416361    131167
224536  0972066713    197450

In [29]:
# Remove rows from books where ISBN is not in the ratings dataset
books = books[books['ISBN'].isin(ratings['ISBN'])]
books.head(10)

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L,Book-Title-Modified,ISBN_new
18118,0312956762,Die Hard: With a Vengeance - A Novel,D. Chiel,1995,St Martins Pr,http://images.amazon.com/images/P/0312956762.0...,http://images.amazon.com/images/P/0312956762.0...,http://images.amazon.com/images/P/0312956762.0...,DieHardWithaVengeanceANovel,50519
232912,034545006X,The Taking,J. D. Landis,2003,Ballantine Books,http://images.amazon.com/images/P/034545006X.0...,http://images.amazon.com/images/P/034545006X.0...,http://images.amazon.com/images/P/034545006X.0...,TheTaking,208690
107022,1579651372,Ruskin's Rose: A Venetian Love Story,Mimma Balia,2000,Artisan Publishers,http://images.amazon.com/images/P/1579651372.0...,http://images.amazon.com/images/P/1579651372.0...,http://images.amazon.com/images/P/1579651372.0...,RuskinsRoseAVenetianLoveStory,151838
99357,0440416361,Nsync : The Official Book,'N Sync,1998,Delacorte Press,http://images.amazon.com/images/P/0440416361.0...,http://images.amazon.com/images/P/0440416361.0...,http://images.amazon.com/images/P/0440416361.0...,NsyncTheOfficialBook,131167
224536,0972066713,The Mom-to-Mom Guide to the Baby Years: Review...,142 moms from all over the world,2002,"Sound Bite Press, Inc.",http://images.amazon.com/images/P/0972066713.0...,http://images.amazon.com/images/P/0972066713.0...,http://images.amazon.com/images/P/0972066713.0...,TheMomtoMomGuidetotheBabyYearsReviewsRatingsan...,197450
87995,055301000X,"\A new spirit, a new commitment, a new America...",1977 Inaugural Committee (U.S.),1977,Bantam Books,http://images.amazon.com/images/P/055301000X.0...,http://images.amazon.com/images/P/055301000X.0...,http://images.amazon.com/images/P/055301000X.0...,AnewspiritanewcommitmentanewAmericaTheinaugura...,13875
135777,0874063582,Friendship for Three,1st Graders of Samuel s Nixon School Carnegie ...,1988,Pages Publishing Group,http://images.amazon.com/images/P/0874063582.0...,http://images.amazon.com/images/P/0874063582.0...,http://images.amazon.com/images/P/0874063582.0...,FriendshipforThree,70585
209538,078946697X,"DK Readers: Creating the X-Men, How It All Beg...",2000,DK Publishing Inc,http://images.amazon.com/images/P/078946697X.0...,http://images.amazon.com/images/P/078946697X.0...,http://images.amazon.com/images/P/078946697X.0...,NaN,DKReadersCreatingtheXMenHowItAllBeganLevel4Pro...,42578
221678,0789466953,"DK Readers: Creating the X-Men, How Comic Book...",2000,DK Publishing Inc,http://images.amazon.com/images/P/0789466953.0...,http://images.amazon.com/images/P/0789466953.0...,http://images.amazon.com/images/P/0789466953.0...,NaN,DKReadersCreatingtheXMenHowComicBooksCometoLif...,42577
220731,2070426769,"Peuple du ciel, suivi de 'Les Bergers\"";Jean-M...",2003,Gallimard,http://images.amazon.com/images/P/2070426769.0...,http://images.amazon.com/images/P/2070426769.0...,http://images.amazon.com/images/P/2070426769.0...,NaN,PeupleducielsuivideLesBergersJeanMarieGustaveL...,139173

In [30]:
print(books_original.shape, books.shape)

(271360, 8) (270151, 10)

In [31]:
# Remove rows from ratings where ISBN is not in the books dataset

ratings = ratings.merge(books, on='ISBN', how='right')
ratings.isna().sum()

User-ID                0
ISBN                   0
Book-Rating            0
Book-Title             0
Book-Author            2
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            4
Book-Title-Modified    0
ISBN_new               0
dtype: int64

In [32]:
ratings.ISBN.nunique()

270151

In [33]:
ratings.ISBN_new.nunique()

238827

In [34]:
ratings_modified = ratings[['User-ID', 'ISBN_new', 'Book-Rating']]
ratings_modified = ratings_modified.rename(columns={'ISBN_new': 'Book-ID'})
ratings_modified.head()

   User-ID  Book-ID  Book-Rating
0     4385    50519           10
1   107674    50519            0
2   125692    50519            0
3   226411    50519            0
4   250330   208690            0

In [35]:
books_modified = books[['ISBN_new', 'Book-Title', 'Book-Author']]
books_modified = books_modified.rename(columns={'ISBN_new': 'Book-ID'})
books_modified = books_modified.drop_duplicates(subset='Book-ID')
books_modified.sort_values(by='Book-Author').head(10)
books_modified.shape

(238827, 3)

In [36]:
books_modified.to_csv('data/cleaned_books_modified.csv', index=False)
ratings_modified.to_csv('data/cleaned_ratings_modified.csv', index=False)

In [44]:
# Get the count of how many times each book has been rated

ratings_count = ratings_modified.groupby('Book-ID').size().reset_index(name='Rating-Count')
ratings_count = ratings_count.sort_values(by='Rating-Count', ascending=False)

In [42]:
ratings_count.to_csv('data/ratings_count.csv', index=False)

In [48]:
# Remove books with less than 5 ratings
ratings_reduced = ratings_count[ratings_count['Rating-Count'] >= 10]
ratings_reduced.shape

(17424, 2)

In [49]:
ratings_reduced.head()

        Book-ID  Rating-Count
232914   233941          2502
194567   195438          1295
181934   182756           898
52469     52735           870
5452       5469           838

In [50]:
books_reduced = books_modified[books_modified['Book-ID'].isin(ratings_reduced['Book-ID'])]
books_reduced.shape

(17424, 3)

In [51]:
books_reduced.to_csv('data/cleaned_books_reduced.csv', index=False)

In [53]:
ratings_reduced_df = ratings_modified[ratings_modified['Book-ID'].isin(ratings_reduced['Book-ID'])]
ratings_reduced_df.shape

(576006, 3)

In [54]:
ratings_reduced_df.to_csv('data/cleaned_ratings_reduced.csv', index=False)

In [ ]:
books_original['Year-Of-Publication']